apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.psc.image.imagePullSecrets }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJldS5nY3IuaW8iOiB7CiAgICAgICJhdXRoIjogImIyRjFkR2d5WVdOalpYTnpkRzlyWlc0NmVXRXlPUzVoTUVGWU9VZENaRlk0WldkSVVXbDBOR05IVGtrNGJEQjZaVUZGTlRoNFJHeGFSV0ZGVFVOcmVtVkxTMWR0WHpsMFdXTTFWelZEZUhGS1MybzNWMEpzTVRBemNFOXRkMGQxWjFveVVIa3RjRVV0VEZVd1JYTlhTVlZzTkZSSVRUUlFaM2RtZVUxaU0yaDJSRjgzYkhBd1RHVkhSRFZwTmxkeFFVbHRTREpUYW13dE0yWmhaV1pWVUV0b2VVZElYMGhhYmxsVGRFZGZlV3BFU2xSQ09WaG9VbXh6TWtKbFJGRTRZVU5uV1V0QlUyTlRRVkZCVTBaUlNGVkRjMkpEU0RNMFptcElVemhmU1RRNFpHSnNTbTVWZERoSFVUQXhOelE9IgogICAgfQogIH0KfQ==