apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: psc-ssd
parameters:
  replication-type: none
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
