apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  labels:
    {{- include "psc.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "psc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.psc.service.type }}
  ports:
  - name: http-fc
    protocol: TCP
    port: {{ .Values.psc.service.ports.fc | default "8080" }}
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-configurator-svc
  labels:
    {{- include "psc.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "psc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.psc.service.type }}
  sessionAffinity: ClientIP
  ports:
  - name: http-configurator
    protocol: TCP
    port: {{ default "6080" .Values.psc.service.ports.configurator }}
    targetPort: 6080
