apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  {{- if eq .Values.psc.service.type "LoadBalancer" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  {{- end }}
  labels:
    {{- include "psc.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "psc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.psc.service.type }}
  ports:
  - name: http-fc
    protocol: TCP
    port: {{ .Values.psc.service.ports.fc.port }}
    targetPort: {{ .Values.psc.service.ports.fc.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-configurator-svc
  {{- if eq .Values.psc.service.type "LoadBalancer" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  {{- end }}
  labels:
    {{- include "psc.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "psc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.psc.service.type }}
  ports:
  - name: http-configurator
    protocol: TCP
    port: {{ .Values.psc.service.ports.configurator.port }}
    targetPort: {{ .Values.psc.service.ports.configurator.targetPort }}
