apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psc-cluster-admin
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources: # Here are the resources you can access
  - pods
  - endpoints
  verbs: # That is what you can do with them
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: psc-service-account
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psc-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: psc-cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: psc-service-account
  namespace: {{ .Release.Namespace }}